/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "snowRenderer.h"
/* Header for class org_moo_android_snowcodedemo_JNIWrapper */

#ifndef _Included_org_moo_android_snowcodedemo_JNIWrapper
#define _Included_org_moo_android_snowcodedemo_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_moo_android_snowcodedemo_JNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moo_android_snowcodedemo_JNIWrapper_on_1surface_1created
  (JNIEnv *env, jclass class)
{
	on_surface_created();
}

/*
 * Class:     org_moo_android_snowcodedemo_JNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_moo_android_snowcodedemo_JNIWrapper_on_1surface_1changed
  (JNIEnv *env, jclass class, jint width, jint height)
{
	on_surface_changed((int)width, (int)height);
}

/*
 * Class:     org_moo_android_snowcodedemo_JNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moo_android_snowcodedemo_JNIWrapper_on_1draw_1frame
  (JNIEnv *env, jclass class, jlong deltaTime)
{
	on_draw_frame((long)deltaTime);
}

#ifdef __cplusplus
}
#endif
#endif
