/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class org_moo_android_snowcodedemo_JNIWrapper */

#ifndef _Included_org_moo_android_snowcodedemo_JNIWrapper
#define _Included_org_moo_android_snowcodedemo_JNIWrapper
#ifdef __cplusplus
#include "snowRenderer.h"
extern "C" {
#endif

SnowRenderer* _renderer;

/*
 * Class:     org_moo_android_snowcodedemo_JNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moo_android_snowcodedemo_JNIWrapper_on_1surface_1created
  (JNIEnv *env, jclass class)
{
	_renderer = new SnowRenderer();
	_renderer->onSurfaceCreated();
}

/*
 * Class:     org_moo_android_snowcodedemo_JNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_moo_android_snowcodedemo_JNIWrapper_on_1surface_1changed
  (JNIEnv *env, jclass class, jint width, jint height)
{
	_renderer->onSurfaceChanged((int)width, (int)height);
}

/*
 * Class:     org_moo_android_snowcodedemo_JNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moo_android_snowcodedemo_JNIWrapper_on_1draw_1frame
  (JNIEnv *env, jclass class)
{
	_renderer->onDrawFrame();
}

#ifdef __cplusplus
}
#endif
#endif
